image: registry.howett.net/ghostbin/builder:master
stages:
    - build
    - deploy

variables:
    GO_PACKAGE: "github.com/DHowett/ghostbin"

before_script:
    - "mkdir -p $(dirname $GOPATH/src/$GO_PACKAGE)/build"
    - "ln -s $(pwd) $GOPATH/src/$GO_PACKAGE"
    - "cd $GOPATH/src/$GO_PACKAGE"

build:
    stage: build
    #only:
    #    - production
    script:
        - npm install
        - go get .
        - ./node_modules/grunt-cli/bin/grunt
        - go build -ldflags="-w -s" -o build/ghostbin
        - cp *.yml build/
        - mkdir -p ./build/bin/pygments
        - curl https://bitbucket.org/birkenfeld/pygments-main/get/stable.tar.bz2 | tar -x -j -C ./build/bin/pygments --strip-components=1
    artifacts:
        paths:
            - build/

deploy to production:
    stage: deploy
    image: scratch # This should be ignored: the ghostbin+deploy runner is shell/ssh
    before_script: []
    variables:
        GIT_STRATEGY: none
    tags: [ "ghostbin", "deploy" ]
    when: manual
    dependencies:
        - build
    environment:
        name: production
        url: https://ghostbin.com
    script: |
        DATE=$(date +%Y%m%d%H%M%S)
        mv build /opt/ghostbin/$DATE
        ln -Tsf /opt/ghostbin/$DATE /opt/ghostbin/latest
        sudo systemctl restart ghostbin
