image: registry.howett.net/ghostbin/builder:master
stages:
    - build

variables:
    GO_PACKAGE: "github.com/DHowett/ghostbin"

before_script:
    - "mkdir -p $(dirname $GOPATH/src/$GO_PACKAGE)/build"
    - "ln -s $(pwd) $GOPATH/src/$GO_PACKAGE"
    - "cd $GOPATH/src/$GO_PACKAGE"

build:
    stage: build
    #only:
    #    - production
    script:
        - npm install
        - go get .
        - go build -ldflags="-w -s" -o build/ghostbin
        - "cp *.yml build/"
        - ./node_modules/grunt-cli/bin/grunt
    artifacts:
        paths:
            - build/
