image: registry.howett.net/ghostbin/builder:master
stages:
    - build

variables:
    GO_PACKAGE: "github.com/DHowett/ghostbin"

before_script:
    - "mkdir -p $(dirname $GOPATH/src/$GO_PACKAGE)/build"
    - "ln -s $(pwd) $GOPATH/src/$GO_PACKAGE"
    - "cd $GOPATH/src/$GO_PACKAGE"

build v1-stable:
    stage: build
    only:
        - v1-stable
    script:
        - npm install
        - go get .
        - ./node_modules/grunt-cli/bin/grunt
        - go build -ldflags="-w -s" -o build/ghostbin
        - cp *.yml build/
        - mkdir -p ./build/bin/pygments
        - curl https://bitbucket.org/birkenfeld/pygments-main/get/stable.tar.bz2 | tar -x -j -C ./build/bin/pygments --strip-components=1
    artifacts:
        paths:
            - build/

build master:
    image: golang:alpine
    variables:
        GO_PACKAGE: "howett.net/spectre"
    stage: build
    except:
        - v1-stable
    script:
        - go get $GO_PACKAGE/cmd/spectred
        - mkdir -p build/
        - cp $GOPATH/bin/spectred build/

